### ISSUE TITLE
How install this?

### ISSUE THREAD

**Issue by ryukinix** [gamux/gamux#6]

**Comment by kress95** [comment]
These instructions are for linux, on Windows the configs location is `%AppData/Gamux/gamux.yml`.
You will also have to use node bin/gamux on Windows, and I'm not sure it works XD

    $ git clone git@github.com:gamux/gamux.git`
    $ cd gamux
    $ npm install
    $ sudo ln -s ./bin/gamux /usr/bin
    $ gamux
    $ emacs ~/.gamux/gamux.yml

Setup your steam ID and select a folder for the games., then run `gamux` to check if everything is ok.
If everything is alright, close steam, run `gamux --update` then open it again.

**Comment by kress95** [comment]
This project is still somewhat cancerous, I need to revamp most of it using a better language.
Using `node.js` on Windows is a bad idea since it f*cks the file system so hard that you can't even guarantee that you're able to delete this project from it after running `npm install`.

I'm closing, but feel free to ask questions about this cancer.

**Comment by ryukinix** [comment]
Thanks to protect me about this maligne cancer. I'm really glad about it.
